### ISSUE TITLE
Stackblitz_Übungsabgabe

### ISSUE THREAD

**Issue by GeraldWakolbinger** [rstropek-teaching/turmrechnen-quiz-4ahif-GeraldWakolbinger#1]
Link zum Editor: https://stackblitz.com/edit/turmrechner
Link zur App: https://turmrechner.stackblitz.io

**Comment by rstropek** [comment]
Nearly. Result is not a table, everything else works fine.

Greetings,
Rainer Stropek.

**Comment by GeraldWakolbinger** [comment]
Updated: result is now a table and elements are aligned.

**Comment by rstropek** [comment]
Nice, thank you. Extra point is secured.

Greetings,
Rainer Stropek.
